# fly.toml app configuration file generated for vaultwarden-ncm6vq on 2025-06-20T03:06:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaultwarden-ncm6vq'
primary_region = 'eze'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
